### PR TITLE
Add Nova Wallet to Shiden native extensions

### PR DESCRIPTION
**Pull request by antonkhvorov**
+ Add Nova Wallet to Shiden native extensions

### CODE REVIEW

**Comment by antonkhvorov** [comment]
@niklabh please let me know if something is missing.
JFYI Nova Wallet implements on iOS/Android app Polkadot JS extension and MetaMask protocols

**Comment by Maar-io** [comment]
@antonkhvorov Are you sure you got the right repo for this PR?
@hoonsubin @impelcrypto is this PR for apps?

**Review by Maar-io — CHANGES_REQUESTED** [review]
not for this repo

**Comment by antonkhvorov** [comment]
@Maar-io That PR is to enable Nova Wallet as one of the native wallets for Astar Pass, isn't it?

**Comment by impelcrypto** [comment]
@antonkhvorov @Maar-io @hoonsubin @niklabh 
I'll merge this PR first since the browser in Nova wallet doesn't allow to open http://192.168.1.126:8080

@antonkhvorov 
As spoken, please help fix this behavior in further update.

image

https://user-images.githubusercontent.com/92044428/164982750-baddbb7c-593f-491a-92db-70bce94354ef.MP4

**Comment by impelcrypto** [comment]
Fixed connect wallet error in https://github.com/AstarNetwork/astarbase/pull/27

**Pull request merged**
