### PR TITLE
Showing Registered EVM for Native address

### PR DESCRIPTION
**Pull request by niklabh**
Screenshot from 2022-07-21 12-20-37

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@niklabh 
Thank you but I think we it has got a different problem now. all addresses are now "registered" when you press Metamask button. Let me clarify with a diagram. I'll provide it later. Thanks

**Comment by niklabh** [comment]
Done

**Comment by Kahonnohak** [comment]
@niklabh 

Two things

1) When connecting Native first time, it works as expected. However when try to connect a different Native which is not registered, the status shows 'registered'. This is I think because UI somehow remembers the history?

2) When users mindset is 'EVM first' it is normal for them to think this 'Status' is based on EVM not Native, so that confuses user and wants to know 'What native account does my EVM registered with' . To avoid that can we make the following two changes?

- Status -> Native account Status
- Disable EVM button as default and activate it only if the Native is not registered.

Thanks!!

**Comment by niklabh** [comment]
What happens in case of evm is already registered. Do we show a message that this evm is already registered?

**Comment by Kahonnohak** [comment]
` What happens in case of evm is already registered with different native. Do we show a error message that this evm is already registered with different native?`

Thanks, my understanding was that an EVM account can be registered with multiple Native addresses...? No?

**Pull request merged**
